_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  announcements_feed: 0
  automated_cron: 0
  backup_migrate: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  components: 0
  config: 0
  config_update: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_login: 0
  gin_toolbar: 0
  history: 0
  image: 0
  language: 0
  link: 0
  linkit: 0
  media: 0
  media_bulk_upload: 0
  media_bulk_upload_dropzonejs: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  node: 0
  node_revision_delete: 0
  options: 0
  page_cache: 0
  paragraphs_features: 0
  path: 0
  path_alias: 0
  redirect: 0
  responsive_image: 0
  search: 0
  serialization: 0
  shortcut: 0
  single_content_sync: 0
  svg_image: 0
  svg_image_responsive: 0
  system: 0
  taxonomy: 0
  taxonomy_access_fix: 0
  text: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_sync: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  viewfield: 0
  views_ui: 0
  webp: 0
  workflows: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  paragraphs_ee: 15
  standard: 1000
theme:
  olivero: 0
  claro: 0
  gin: 0
  stable9: 0
  drupalx_theme: 0
  stark: 0
profile: standard
