_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 92a6c61a-5723-44b7-b473-91fb0b0fa6f8
name: 'Drush Site-Install'
mail: admin@example.com
slogan: ''
page:
  403: /node/18
  404: /node/5
  front: /node/16
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
